cloud_topic: /fastlio2/body_cloud
odom_topic: /fastlio2/lio_odom
map_frame: map
local_frame: odom_fastlio
update_hz: 0.2

rough_scan_resolution: 0.25
rough_map_resolution: 0.5
rough_max_iteration: 50
rough_score_thresh: 5.0

refine_scan_resolution: 0.1
refine_map_resolution: 0.3
refine_max_iteration: 80
refine_score_thresh: 2.0
